import type { Permission } from "@/framework/types/entity";
import { PermissionType } from "@/framework/types/enum";

const routes: Permission[] = [
	{
		order: 1,
		id: "dashboard",
		parentId: "",
		label: "app.dashboard",
		name: "Dashboard",
		icon: "solar:widget-broken",
		type: PermissionType.MENU,
		route: "dashboard",
		component: "/content/dashboard/index.tsx",
	},
	{
		order: 1,
		id: "programs",
		parentId: "",
		label: "app.programs.title",
		name: "Programs",
		icon: "solar:backpack-broken",
		type: PermissionType.MENU,
		route: "programs",
		component: "/content/programs/index.tsx",
	},
	{
		order: 1,
		id: "programs-builder",
		parentId: "programs",
		label: "app.programs.builder.title",
		name: "Program Builder",
		icon: "solar:backpack-broken",
		type: PermissionType.MENU,
		route: "programs/builder",
		hide: true,
		component: "/content/programs/builder/index.tsx",
	},
	{
		order: 1,
		id: "programs-builder-edit",
		parentId: "programs",
		label: "app.programs.builder.title",
		name: "Program Builder Edit",
		icon: "solar:backpack-broken",
		type: PermissionType.MENU,
		route: "programs/builder/:id",
		hide: true,
		component: "/content/programs/builder/index.tsx",
	},
	{
		order: 1,
		id: "levels",
		parentId: "",
		label: "app.levels.title",
		name: "Levels",
		icon: "solar:layers-minimalistic-broken",
		type: PermissionType.MENU,
		route: "levels",
		component: "/content/levels/index.tsx",
	},
	{
		order: 1,
		id: "subjects",
		parentId: "",
		label: "app.subjects.title",
		name: "Subjects",
		icon: "solar:book-2-broken",
		type: PermissionType.MENU,
		route: "subjects",
		component: "/content/subjects/index.tsx",
	},
	{
		order: 1,
		id: "lessons",
		parentId: "",
		label: "app.lessons.title",
		name: "Lessons",
		icon: "solar:video-frame-play-horizontal-broken",
		type: PermissionType.MENU,
		route: "lessons",
		component: "/content/lessons/index.tsx",
	},
	{
		order: 1,
		id: "tasks",
		parentId: "",
		label: "app.tasks.title",
		name: "Tasks",
		icon: "solar:bill-list-broken",
		type: PermissionType.MENU,
		route: "tasks",
		component: "/content/tasks/index.tsx",
	},
	{
		order: 1,
		id: "assignments",
		parentId: "",
		label: "app.assignments.menu-title",
		name: "Assignments",
		icon: "solar:clipboard-list-broken",
		type: PermissionType.MENU,
		route: "assignments",
		component: "/content/assignments/index.tsx",
	},
	{
		order: 1,
		id: "assignments-responses-show",
		parentId: "assignments-responses",
		label: "app.assignmentResponses.title",
		name: "Assignment response",
		icon: "ri:newspaper-line",
		type: PermissionType.MENU,
		hide: true,
		route: "responses/:responseId",
		component: "/content/assignment-responses/show.tsx",
	},
	{
		order: 1,
		id: "assignments-responses",
		parentId: "",
		label: "app.assignments.title",
		name: "Assignment responses",
		icon: "ri:newspaper-line",
		type: PermissionType.MENU,
		route: "assignments/:assignmentId/responses",
		hide: true,
		component: "/content/assignment-responses/index.tsx",
		// children: [
		// 		{
		// 			order: 1,
		// 			id: "assignments-responses-show",
		// 			parentId: "assignments-responses",
		// 			label: "app.assignments.title",
		// 			name: "Assignment response",
		// 			icon: "ri:newspaper-line",
		// 			type: PermissionType.MENU,
		// 			route: ":responseId",
		// 			component: "/content/assignment-responses/show.tsx",
		// 		},
		// ]
	},
	{
		order: 1,
		id: "subscriptions",
		parentId: "",
		label: "app.subscriptions.title",
		name: "Tasks",
		icon: "solar:people-nearby-broken",
		type: PermissionType.MENU,
		route: "subscriptions",
		component: "/content/subscriptions/index.tsx",
	},
];

export default routes;
